#ifndef GENERATED_ASN1SCC_Context_test_rigidbodystatedisapatcherproducer_H
#define GENERATED_ASN1SCC_Context_test_rigidbodystatedisapatcherproducer_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_test_rigidbodystatedisapatcherproducer --------------------------------------------*/

typedef struct {
    asn1SccT_Float init_val;
    asn1SccT_Float inc;

} asn1SccContext_test_rigidbodystatedisapatcherproducer;

flag asn1SccContext_test_rigidbodystatedisapatcherproducer_Equal(const asn1SccContext_test_rigidbodystatedisapatcherproducer* pVal1, const asn1SccContext_test_rigidbodystatedisapatcherproducer* pVal2);

void asn1SccContext_test_rigidbodystatedisapatcherproducer_Initialize(asn1SccContext_test_rigidbodystatedisapatcherproducer* pVal);

#define ERR_CONTEXT_TEST_RIGIDBODYSTATEDISAPATCHERPRODUCER_INIT_VAL		1  /**/
#define ERR_CONTEXT_TEST_RIGIDBODYSTATEDISAPATCHERPRODUCER_INC		12  /**/
flag asn1SccContext_test_rigidbodystatedisapatcherproducer_IsConstraintValid(const asn1SccContext_test_rigidbodystatedisapatcherproducer* pVal, int* pErrCode);

extern const asn1SccContext_test_rigidbodystatedisapatcherproducer test_rigidbodystatedisapatcherproducer_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif