/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-markermux.h"


const asn1SccContext_markermux markermux_ctxt = {
    .marker0 = 352,
    .marker1 = 404
};


flag asn1SccContext_markermux_Equal(const asn1SccContext_markermux* pVal1, const asn1SccContext_markermux* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->marker0 == pVal2->marker0);

    if (ret) {
        ret = (pVal1->marker1 == pVal2->marker1);

    }
	return ret;

}

void asn1SccContext_markermux_Initialize(asn1SccContext_markermux* pVal)
{


	/*set marker0 */
	asn1SccT_Int32_Initialize((&(pVal->marker0)));
	/*set marker1 */
	asn1SccT_Int32_Initialize((&(pVal->marker1)));
}

flag asn1SccContext_markermux_IsConstraintValid(const asn1SccContext_markermux *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((-2147483648LL <= pVal->marker0) && (pVal->marker0 <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_CONTEXT_MARKERMUX_MARKER0;
    if (ret) {
        ret = ((-2147483648LL <= pVal->marker1) && (pVal->marker1 <= 2147483647LL));
        *pErrCode = ret ? 0 :  ERR_CONTEXT_MARKERMUX_MARKER1;
    }

	return ret;
}

