#ifndef GENERATED_ASN1SCC_Context_markermux_H
#define GENERATED_ASN1SCC_Context_markermux_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_markermux --------------------------------------------*/

typedef struct {
    asn1SccT_Int32 marker0;
    asn1SccT_Int32 marker1;

} asn1SccContext_markermux;

flag asn1SccContext_markermux_Equal(const asn1SccContext_markermux* pVal1, const asn1SccContext_markermux* pVal2);

void asn1SccContext_markermux_Initialize(asn1SccContext_markermux* pVal);

#define ERR_CONTEXT_MARKERMUX_MARKER0		1  /**/
#define ERR_CONTEXT_MARKERMUX_MARKER1		12  /**/
flag asn1SccContext_markermux_IsConstraintValid(const asn1SccContext_markermux* pVal, int* pErrCode);

extern const asn1SccContext_markermux markermux_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif